### ISSUE TITLE
GetOSName should support Windows 10, 2012

### ISSUE THREAD

**Issue by sparvu** [jandubois/win32#10]
Any ideas when we should see full support for Windows 10 and 2012 Server for GetOSName ?

We are developing using ActiveState 5.20.2 and PDK 9.4 and I did upgrade the perl modules but still some people are complaining that [hdwrec]
(https://github.com/kronometrix/recording/blob/master/bin/windows/hdwrec)   cannot report correctly on Windows OS name and release version.

I see from changelog, that the support is not entirely implemented. Is this correct ?

0.52 [2015-08-19]
- minimal Windows 10 support (thanks to Joel Maslak) [PR/8]
- refactor Windows 10 support to include ProductInfo flags
- add tests for Windows 8.1, 10, and 2012 R2 server
- define additional ProductInfo flags (TODO: add support for
these codes in _GetOSName)

**Comment by jandubois** [comment]
> Any ideas when we should see full support for Windows 10 and 2012 Server for GetOSName ?

I think this is already working.

> I see from changelog, that the support is not entirely implemented. Is this correct ?

What could be improved would be the logic for GetOSDisplayName() for Windows 10/2012 Server, to assign the correct "marketing" names to the various editions of Windows. Right now it uses the same code as was used for Windows 8, which sometimes gives incorrect results (e.g. uses "Business" instead of "Pro").

But for all this code to work, the Perl executable needs to be built with an updated manifest that claims compatibility with these newer versions of Windows; otherwise Windows will lie about which version it actually is:

http://perl5.git.perl.org/perl.git/commitdiff/9964c51

So until this changes makes it's way into the ActivePerl distributions, you will still see Windows 10 reported as Windows 8, even when the Win32 is up-to-date.
